server:
  context-path: /desafio-java
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:concrete-solutions;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql : true
  h2:
    console:
      enabled: true
      path: /h2-console